### PR TITLE
Add meetup-10 info and change links layout

### PR DESCRIPTION
**Pull request by lucianomlima**
A new proposal how to show links. What do you think?

### CODE REVIEW

**Comment by vhfmag** [comment]
A screenshot would have been great :laughing: 

Before:
image

After:
image

**Review by vhfmag — COMMENTED** [review]
Awesome!

**Comment by lucianomlima** [comment]
> A screenshot would have been great 😆

Ouch... I take a screenshot but forget to put in description! LOL! 🤣

**Comment by vhfmag** [comment]
No problems, didn't mean to be rude :upside_down_face:

**Review by vhfmag — APPROVED** [review]
Awesome (and again I thought that `ctrl enter` would approve the PR, but it just adds a comment :disappointed:)

**Pull request merged**
